### ISSUE TITLE
Messages are resent when refreshing a page after sending

### ISSUE THREAD

**Issue by milofultz** [cblgh/cerca#10]
When I refresh the page after submitting a post on an existing thread, it submits the same post request again. 

I figure if we are using a static (i.e. non-JS driven) forum, refreshes should be the norm of seeing if something new happened, so ensuring this doesn't happen seems like a good idea. 

I'll dig around and see if I can put my finger on what could be done, but I am not anywhere near Go, so somebody else could probably spot it before I even get my shoes on

### Steps to reproduce the bug

* Go to the test thread.
* Enter in some text in the textarea.
* Click "Post".
* Once the page loads, you should see the new post.
* Refresh the page. You should see a duplicate of the original post.

**Comment by milofultz** [comment]
Seems like this [PRG kind of scenario](https://en.wikipedia.org/wiki/Post/Redirect/Get) would be the solution, but not sure how to implement.

I see [here](https://github.com/cblgh/cerca/blob/142a10de16a7ca0fb83016fbfe2466a80e2de0bd/server/server.go#L149) that I think this was the goal, too: `after handling a post, treat the request as if it was a get request`. Again, not really sure if this is right, but maybe should respond with the successful POST with a 303 pointing at the current thread? I'll keep digging into this and see if I can come up with the solution

**Comment by milofultz** [comment]
[This looks pretty close to a solution](https://stackoverflow.com/questions/36345696/http-redirect-with-headers), explicitly mentioning the PRG solution.

**Comment by cblgh** [comment]
great research @milofultz, very much appreciated! as a result it should be fixed, i believe?
