### ISSUE TITLE
Timestamps needs a bit of margin-left

### ISSUE THREAD

**Issue by neauoire** [cblgh/cerca#12]
![2022-01-12-085033_1366x768_scrot](https://user-images.githubusercontent.com/1455726/149184853-701f8887-f70d-4ca4-9b0f-8fe8b32d1954.png)

**Comment by cblgh** [comment]
probably solved: https://github.com/cblgh/cerca/commit/952b7f855724e2f65fd775a26bb656355d9eaff0

lemme know if it doesn't suffice!
