### ISSUE TITLE
Webring domain not in allowlist

### ISSUE THREAD

**Issue by non** [cblgh/cerca#28]
I'm seeing the following error when trying to register for the forum:

> Verification link's host (plastic-idolatry.com) is not in the allowlist 

This domain was added to the webring recently. Is it possible the server needs to be restarted or something? Does the service pick up new domains dynamically?

**Comment by cblgh** [comment]
fixed for you in https://github.com/cblgh/cerca/commit/876816629365fe88a7e7704d40be808fe89bcc02 i reckon!

for the future: there needs to be a periodic scraping action (in a goroutine likely) that updates the allowlist; i might just run `lieu precrawl` as a recurring shell script or sth lol

please re-open if the fix didn't work for ya @non

**Comment by plungepool** [comment]
Piggybacking onto this issue - no rush but experiencing the same thing as above. I was only added to the webring today however, so if updating the allowlist requires a redeployment I am fine with waiting until whenever that is convenient!
