### ISSUE TITLE
"Jump to Bottom" Link is Missing

### ISSUE THREAD

**Issue by JakeMBauer** [cblgh/cerca#41]
Hello o/

There is normally a link in the header when viewing a thread that lets you jump down to the bottom of the thread, but it has gone missing sometime within the past month or so. The link element seems to still be there, but the text between the <a></a> tag is not.

See image below for illustration:

![image](https://user-images.githubusercontent.com/32146222/208254755-a3bd0c04-0c7e-4de2-9358-ebf37e0878e0.png)

**Comment by cblgh** [comment]
oh good catch! might be a mistake arising from the translation sprint i did, will have a look at it :>

**Comment by cblgh** [comment]
gotem :~
