### ISSUE TITLE
Edit support for posts

### ISSUE THREAD

**Issue by stevenleeg** [cblgh/cerca#42]
I just made [a post](https://forum.merveilles.town/thread/11/food%21-23/#1282) on the Merveilles forum and, after hitting submit, realized that the formatting was off for my ordered list. The lack of edit functionality makes it so I can't go back and correct it which made me think of this.

Is there any interest in adding this functionality?

**Comment by cblgh** [comment]
@stevenleeg thanks for the issue and the clear example. yes, edit would be fabulous to have for this exact reason! there is interest in having it. are you interested in adding it, i could share some of guiding thoughts on how i'd go about it?

**Comment by alexwennerberg** [comment]
Started working on this. Went with a no-JS solution. Need to find some way to redirect back to the original thread though (and do a bit of cleanup / error handling)

https://github.com/cblgh/cerca/compare/main...alexwennerberg:cerca:edit

**Comment by cblgh** [comment]
nice :) something i was considering for the addition of edit was to simultaneously fix the problem of "oh no my markdown wasn't right" in that the authoring step could also have a preview button

so perhaps something like
``` 
[ textarea ]

[ post ] [ preview ]
```

where post works like it does today to not introduce any friction when posting, and preview could potentially re-use the edit view for displaying the post. 

one way the edit view could be reused: perhaps by conditionally embedding a textarea below the rendered message one could iterate on the post and, when content, click "post". at which point the post actually is saved in the database. alternatively one could be directed to _go back_ to edit the content

**Comment by alexwennerberg** [comment]
Made a few changes in https://github.com/cblgh/cerca/commit/087acb35d5c3da69b56df30394f4de43f60f0398 to render HTML alongside the edit page

Changed markup to take a `string` instead of a `template.HTML` and moving the rendering to a template function. I think this makes sense, bc a markdown string is a. not HTML and b. not necessarily safe to render -- let me know what you think

**Comment by cblgh** [comment]
i think i like it! can you share a screenshot of what it currently looks like? i'd be curious to see :>

**Comment by alexwennerberg** [comment]
Will do! It is a rainy weekend in New York so I should be able to put together some PRsAlexOn Jan 6, 2024, at 9:37 AM, Alexander Cobleigh ***@***.***> wrote:﻿
i think i like it! can you share a screenshot of what it currently looks like? i'd be curious to see :>

**Comment by alexwennerberg** [comment]
![edit](https://github.com/cblgh/cerca/assets/11624958/b123dc02-2983-4cc7-8e9f-c6e5ea8b2c25)

**Comment by cblgh** [comment]
we've got it IN #54 thanks @alexwennerberg
