### ISSUE TITLE
Open singups discussion

### ISSUE THREAD

**Issue by alexwennerberg** [cblgh/cerca#62]
Sorry for all the issues today, I've been doing a lot of work on cerca haha

I've been working on an optional boolean to allow open singups. This involve creating a concept of shadowbanned / "hidden" users. Posts by these users are visible only to themselves and admins

admins can then either unhide a user's account, or ban them if they are spammers. This allows users to participate immediately without something like email confirmation, while also locking spammers out of making posts (while giving them no visible feedback that their posts are invisible)

I would imagine this isn't necessarily what cerca is originally designed for, but I don't think it deviates too far -- and I think it makes it easier for small communities where an admin can simply ban anyone who isn't in the targeted community, while also making it so it's easier for people to sign up 

WIP implementation on aw-fork2

#59 is intended to lay the groundwork for this, simply so people can't extremely trivially ddos the server and make the site unusable for admins

**Comment by alexwennerberg** [comment]
I thought about this a bit and have some different thoughts. I think the 'shadowban' thing was too complex and unnecessary. Instead, I basically just copied what I do on https://flounder.online/

User creates account with a brief description of where they came from -> they are set as pending = true, and cannot make posts -> admin approves them

A really hacky version of this is on my PR (it is not very clean but just a demo to experiment with for now)

**Comment by cblgh** [comment]
open signups can now be implemented by creating a public thread that contains a reusable invite in it :)
