### ISSUE TITLE
verification_explanation  -> verification_instructions in sample-config.toml?

### ISSUE THREAD

**Issue by decentral1se** [cblgh/cerca#72]
The default config seems to have an out-of-date key?

https://github.com/cblgh/cerca/blob/1f4d8ff974ed2314293e5bdc051bfa9f17031c0e/defaults/sample-config.toml#L15

**Comment by cblgh** [comment]
may be rendered irrelevant by way of #75

**Comment by cblgh** [comment]
closing for now
