### ISSUE TITLE
Look into how to enable alt text syntax for images

### ISSUE THREAD

**Issue by decentral1se** [cblgh/cerca#80]
If I do this in a post:

`![my alt text](https://...)`

I get:

`<p><img loading="lazy" src="https://..."/></p>`

The `alt="my alt text"` doesn't seem to make it through the conversion?

**Comment by cblgh** [comment]
oh dang, the differences in markdown renderers. it probably never worked in that case!

**Comment by decentral1se** [comment]
Nice, yes, that looks promising. Thanks for looking into it.

Issue upstreamed in the meantime: https://github.com/gomarkdown/markdown/issues/318

**Comment by decentral1se** [comment]
Oh nice some source codez https://github.com/gomarkdown/markdown/issues/318#issuecomment-2423238722

**Comment by cblgh** [comment]
@decentral1se i'm now using the alt text to also set the `title` attribute :) check out https://github.com/cblgh/cerca/commit/e478e28fa683558913d5483d3ec16c4e6b4ddb64

**Comment by decentral1se** [comment]
oh sheeeyat, that's great stuff! ok lemme do a test on the forum / dev instance and hopefully we can close this one out 🙏 nice detective work & patch!
