### ISSUE TITLE
Unable to edit thread title after creation

### ISSUE THREAD

**Issue by decentral1se** [cblgh/cerca#81]
I can edit the first post content, but not the title. Current work-around is to copy/pasta the content, delete the entire thread and re-create the thread. This is fine for new threads but wouldn't work for threads that have discussion (unless you don't mind losing it all). Edits later on might be handy to signal things are resolved/over/etc.

**Comment by 320x200** [comment]
![not sure if renaming the issue was accidental—OR A SUBTLE WAY TO MAKE A POINT](https://bleu255.com/~aymeric/dump/974lwl.jpg)

**Comment by cblgh** [comment]
:] it's a relic from when there was no edit function. if this seems important for your usage, then we can add it! would probably mean changing the "current edit post" view / copying it to also enable changing the thread title if you are the thread author

**Comment by decentral1se** [comment]
nice, thx! yeh it seems pretty critical for pmc needs as we reflected on how to do some sort of categorisation/overview based on `[...]` in the titles (e.g. `[event] my cool event`) (and gardening those after people create threads in case they miss the convention). will take a stab at this 🎉

**Comment by cblgh** [comment]
>  (and gardening those after people create threads in case they miss the convention)

oh so this is a sneaky requirement! you mean to allow admins to change titles after a user has created a post? will have to think about this, it's a paradigm change :] currently all admins do are glorified doorkeepers (letting people in and kicking abuse out). but once everybody is in, there is no surreptitious editing / hiding of other users posts that are available on other forums

anyway, i will up-prioritize the `[...]` explorations! it's [been asked of in the forum previously](https://forum.merveilles.town/thread/94/diving-into-thread-categories-9/)

**Comment by decentral1se** [comment]
> oh so this is a sneaky requirement!

oh you're right! wait a sec, i think im imagining that one so we can hold off until someone from admin world asks for that? the obvious workaround is a comment to ask the poster to adjust the title which is probably fine.

filter energy is exciting! h&d are cool 💘

**Comment by cblgh** [comment]
> the obvious workaround is a comment to ask the poster to adjust the title which is probably fine

yeah i reckon we start there too :] 🖤

**Comment by decentral1se** [comment]
Aight, I'm gonna get a PR out for this one. Coming Soon!

**Comment by cblgh** [comment]
so psyched!!! 👀

**Comment by decentral1se** [comment]
@cblgh whatcha reckon for UI on this?

a separate "edit" button on the title itself (if you created the thread) with accompanying "edit-title.html". *or* include the title in the "edit-post.html" when you click "edit" on the first post (where you chose the title originally).

the latter feels more consistent but i think without some additional indication of some sort, it will be confusing if you never edited a title before. Maybe modifying the "edit delete" hrefs to "edit (post and title) delete" for the first post in the thread?

**Comment by cblgh** [comment]
i was thinking that for the opening post the thread title could be a simple input box that is also populated, similar to the textarea that is populated and edited for post contents? then to check if its contents has changed and if so call the database accordingly

so that would probably be what you're saying here

> or include the title in the "edit-post.html" when you click "edit" on the first post (where you chose the title originally)


> Maybe modifying the "edit delete" hrefs to "edit (post and title) delete" for the first post in the thread?

this sounds like a really good way of signaling it! shorter, but perhaps less descriptive: "edit thread"?
