### ISSUE TITLE
Persistent sort choice and visual indication of choice?

### ISSUE THREAD

**Issue by decentral1se** [cblgh/cerca#97]
AFAICT "most recent threads" is the default?

If you change this, it is persisted on page reload, as long as you do not leave the threads page. If you, say, hit the about page, the sort is reset.

Can we persist the choice across different page loads? AFAICT, this is done for the filters, so I guess we need to deal with putting something in the session?

Similarly to how filters were dealt with, I think it would be nice to have some visual indication of the sorting type? I'm not sure where best to put it.

(*No rush while you're hacking on* https://github.com/cblgh/cerca/pull/92 😌)

**Comment by cblgh** [comment]
> Can we persist the choice across different page loads? AFAICT, this is done for the filters

i think i already do this as of the change in https://github.com/cblgh/cerca/pull/89, can you check again against your test deployment and lmk?

**Comment by decentral1se** [comment]
> i think i already do this as of the change in https://github.com/cblgh/cerca/pull/89

I just tried a fresh update of the latest changes and I can't see to get any threads listed on the main home page when I create them now? Maybe something weird with my cache but I did try to refresh it 🤔

**Comment by cblgh** [comment]
i'll look into it!!
